/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#233143",
        "secondary": "#7bd0ff",
        "inverse-surface": "#dae2fd",
        "secondary-fixed-dim": "#7bd0ff",
        "on-tertiary-fixed-variant": "#39485a",
        "surface-container-highest": "#2d3449",
        "on-secondary-fixed-variant": "#004c69",
        "on-tertiary-fixed": "#0d1c2d",
        "inverse-primary": "#006e2f",
        "on-secondary-container": "#00374d",
        "surface": "#0b1326",
        "on-surface": "#dae2fd",
        "on-error-container": "#ffdad6",
        "on-secondary": "#00354a",
        "secondary-container": "#00a6e0",
        "surface-dim": "#0b1326",
        "primary": "#4be277",
        "primary-container": "#22c55e",
        "tertiary-fixed-dim": "#b9c8de",
        "outline-variant": "#3d4a3d",
        "tertiary-container": "#9eadc2",
        "inverse-on-surface": "#283044",
        "surface-container-low": "#131b2e",
        "on-secondary-fixed": "#001e2c",
        "surface-tint": "#4ae176",
        "surface-bright": "#31394d",
        "on-background": "#dae2fd",
        "tertiary-fixed": "#d4e4fa",
        "on-surface-variant": "#bccbb9",
        "primary-fixed-dim": "#4ae176",
        "on-primary-fixed-variant": "#005321",
        "on-primary": "#003915",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "primary-fixed": "#6bff8f",
        "background": "#0b1326",
        "on-tertiary-container": "#334153",
        "surface-container-high": "#222a3d",
        "tertiary": "#b9c8de",
        "on-primary-fixed": "#002109",
        "on-primary-container": "#004b1e",
        "surface-container": "#171f33",
        "surface-container-lowest": "#060e20",
        "secondary-fixed": "#c4e7ff",
        "on-error": "#690005",
        "surface-variant": "#2d3449",
        "outline": "#869585",
        "macro-fat": "#ffb74d"
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["Manrope"],
        label: ["Manrope"]
      }
    },
  },
  plugins: [],
}
